package com.javasm.product.dao;

import com.javasm.base.bean.PageInfo;
import com.javasm.product.bean.BkProduct;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BkProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_product
     *
     * @mbggenerated Wed Oct 19 10:59:26 CST 2022
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_product
     *
     * @mbggenerated Wed Oct 19 10:59:26 CST 2022
     */
    int insert(BkProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_product
     *
     * @mbggenerated Wed Oct 19 10:59:26 CST 2022
     */
    BkProduct selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_product
     *
     * @mbggenerated Wed Oct 19 10:59:26 CST 2022
     */
    List<BkProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bk_product
     *
     * @mbggenerated Wed Oct 19 10:59:26 CST 2022
     */
    int updateByPrimaryKey(BkProduct record);


    List<BkProduct> queryByConditionForPage(@Param("pageInfo")PageInfo pageInfo, @Param("p") BkProduct bkProduct);


    int getTotal(@Param("p") BkProduct bkProduct);


    /**
     * 查询当前登录人可看到的审核产品
     * @param pageInfo
     * @param bkProduct
     * @param adminId
     * @return
     */
    List<BkProduct> queryByConditionForPageAndAudit(@Param("pageInfo")PageInfo pageInfo, @Param("p") BkProduct bkProduct ,@Param("adminId") Integer adminId);


    int getTotalForAudit(@Param("p") BkProduct bkProduct,@Param("adminId") Integer adminId);


    /**
     * 查询和productId相关联的产品id集合
     * @param productId
     * @return
     */
    Integer[] selectRelatedIdsByProductId(@Param("productId") Integer productId);


    Integer[] selectNoRelatedIdsByProductId(@Param("productId")Integer productId);
}