package com.javasm.product.dao;

import com.javasm.product.bean.ProductNet;
import java.util.List;

public interface ProductNetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_net
     *
     * @mbggenerated Wed Oct 19 22:35:03 CST 2022
     */
    int deleteByPrimaryKey(Integer netId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_net
     *
     * @mbggenerated Wed Oct 19 22:35:03 CST 2022
     */
    int insert(ProductNet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_net
     *
     * @mbggenerated Wed Oct 19 22:35:03 CST 2022
     */
    ProductNet selectByPrimaryKey(Integer netId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_net
     *
     * @mbggenerated Wed Oct 19 22:35:03 CST 2022
     */
    List<ProductNet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_net
     *
     * @mbggenerated Wed Oct 19 22:35:03 CST 2022
     */
    int updateByPrimaryKey(ProductNet record);
}