package com.javasm.product.dao;

import com.javasm.base.annotation.RequestParam;
import com.javasm.base.bean.PageInfo;
import com.javasm.product.bean.Recommend;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    int deleteByPrimaryKey(Integer recommendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    Recommend selectByPrimaryKey(Integer recommendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    List<Recommend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    int updateByPrimaryKey(Recommend record);


    List<Recommend> queryByConditionForPage(@Param("pageInfo") PageInfo<Recommend> pageInfo, @Param("productName") String productName);

    /**
     * 查询总记录数
     * @param productName
     * @return
     */
    int getTotal( @Param("productName") String productName);

}