package com.javasm.product.bean;

public class BkProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_type.product_type_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer productTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_type.product_type_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String productTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_type.type_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_type.parent_type
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer parentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_type.product_type_id
     *
     * @return the value of bk_product_type.product_type_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_type.product_type_id
     *
     * @param productTypeId the value for bk_product_type.product_type_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_type.product_type_name
     *
     * @return the value of bk_product_type.product_type_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_type.product_type_name
     *
     * @param productTypeName the value for bk_product_type.product_type_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName == null ? null : productTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_type.type_id
     *
     * @return the value of bk_product_type.type_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_type.type_id
     *
     * @param typeId the value for bk_product_type.type_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_type.parent_type
     *
     * @return the value of bk_product_type.parent_type
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getParentType() {
        return parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_type.parent_type
     *
     * @param parentType the value for bk_product_type.parent_type
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setParentType(Integer parentType) {
        this.parentType = parentType;
    }
}