package com.javasm.product.bean;

public class BkProductLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_line.product_line_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer productLineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_line.product_line_qudao
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer productLineQudao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_line.product_line_type
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer productLineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_line.product_line_chinese_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String productLineChineseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_line.product_line_english_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String productLineEnglishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bk_product_line.collection_bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String collectionBankName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_line.product_line_id
     *
     * @return the value of bk_product_line.product_line_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getProductLineId() {
        return productLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_line.product_line_id
     *
     * @param productLineId the value for bk_product_line.product_line_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductLineId(Integer productLineId) {
        this.productLineId = productLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_line.product_line_qudao
     *
     * @return the value of bk_product_line.product_line_qudao
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getProductLineQudao() {
        return productLineQudao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_line.product_line_qudao
     *
     * @param productLineQudao the value for bk_product_line.product_line_qudao
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductLineQudao(Integer productLineQudao) {
        this.productLineQudao = productLineQudao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_line.product_line_type
     *
     * @return the value of bk_product_line.product_line_type
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getProductLineType() {
        return productLineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_line.product_line_type
     *
     * @param productLineType the value for bk_product_line.product_line_type
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductLineType(Integer productLineType) {
        this.productLineType = productLineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_line.product_line_chinese_name
     *
     * @return the value of bk_product_line.product_line_chinese_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getProductLineChineseName() {
        return productLineChineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_line.product_line_chinese_name
     *
     * @param productLineChineseName the value for bk_product_line.product_line_chinese_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductLineChineseName(String productLineChineseName) {
        this.productLineChineseName = productLineChineseName == null ? null : productLineChineseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_line.product_line_english_name
     *
     * @return the value of bk_product_line.product_line_english_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getProductLineEnglishName() {
        return productLineEnglishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_line.product_line_english_name
     *
     * @param productLineEnglishName the value for bk_product_line.product_line_english_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductLineEnglishName(String productLineEnglishName) {
        this.productLineEnglishName = productLineEnglishName == null ? null : productLineEnglishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bk_product_line.collection_bank_name
     *
     * @return the value of bk_product_line.collection_bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getCollectionBankName() {
        return collectionBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bk_product_line.collection_bank_name
     *
     * @param collectionBankName the value for bk_product_line.collection_bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setCollectionBankName(String collectionBankName) {
        this.collectionBankName = collectionBankName == null ? null : collectionBankName.trim();
    }
}