package com.javasm.product.bean;

public class Recommend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.recommend_id
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer recommendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.product_id
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.is_visable
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer isVisable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.is_first
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer isFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.online_subscription
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer onlineSubscription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.description
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.ordered
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer ordered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.recommend_degree
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer recommendDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.admin
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    private Integer admin;


    private String productName;

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.recommend_id
     *
     * @return the value of recommend.recommend_id
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.recommend_id
     *
     * @param recommendId the value for recommend.recommend_id
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setRecommendId(Integer recommendId) {
        this.recommendId = recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.product_id
     *
     * @return the value of recommend.product_id
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.product_id
     *
     * @param productId the value for recommend.product_id
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.is_visable
     *
     * @return the value of recommend.is_visable
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getIsVisable() {
        return isVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.is_visable
     *
     * @param isVisable the value for recommend.is_visable
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setIsVisable(Integer isVisable) {
        this.isVisable = isVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.is_first
     *
     * @return the value of recommend.is_first
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getIsFirst() {
        return isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.is_first
     *
     * @param isFirst the value for recommend.is_first
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setIsFirst(Integer isFirst) {
        this.isFirst = isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.online_subscription
     *
     * @return the value of recommend.online_subscription
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getOnlineSubscription() {
        return onlineSubscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.online_subscription
     *
     * @param onlineSubscription the value for recommend.online_subscription
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setOnlineSubscription(Integer onlineSubscription) {
        this.onlineSubscription = onlineSubscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.description
     *
     * @return the value of recommend.description
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.description
     *
     * @param description the value for recommend.description
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.ordered
     *
     * @return the value of recommend.ordered
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.ordered
     *
     * @param ordered the value for recommend.ordered
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.recommend_degree
     *
     * @return the value of recommend.recommend_degree
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getRecommendDegree() {
        return recommendDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.recommend_degree
     *
     * @param recommendDegree the value for recommend.recommend_degree
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setRecommendDegree(Integer recommendDegree) {
        this.recommendDegree = recommendDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.admin
     *
     * @return the value of recommend.admin
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public Integer getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.admin
     *
     * @param admin the value for recommend.admin
     *
     * @mbggenerated Thu Oct 20 14:30:30 CST 2022
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }
}