package com.javasm.product.bean;

public class Remittance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.remittance_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer remittanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.bankSWIFT
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String bankswift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.bank_code
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.CNAPS
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String cnaps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.collection_bank_area
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String collectionBankArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.collection_bank_city
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String collectionBankCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.collection_bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String collectionBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.colletion_bank_accout
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String collectionBankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.account_address
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String accountAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.manageMent
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private String management;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remittance.product_line_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    private Integer productLineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.remittance_id
     *
     * @return the value of remittance.remittance_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getRemittanceId() {
        return remittanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.remittance_id
     *
     * @param remittanceId the value for remittance.remittance_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setRemittanceId(Integer remittanceId) {
        this.remittanceId = remittanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.bank_name
     *
     * @return the value of remittance.bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.bank_name
     *
     * @param bankName the value for remittance.bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.bankSWIFT
     *
     * @return the value of remittance.bankSWIFT
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getBankswift() {
        return bankswift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.bankSWIFT
     *
     * @param bankswift the value for remittance.bankSWIFT
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setBankswift(String bankswift) {
        this.bankswift = bankswift == null ? null : bankswift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.bank_code
     *
     * @return the value of remittance.bank_code
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.bank_code
     *
     * @param bankCode the value for remittance.bank_code
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.CNAPS
     *
     * @return the value of remittance.CNAPS
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getCnaps() {
        return cnaps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.CNAPS
     *
     * @param cnaps the value for remittance.CNAPS
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setCnaps(String cnaps) {
        this.cnaps = cnaps == null ? null : cnaps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.collection_bank_area
     *
     * @return the value of remittance.collection_bank_area
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getCollectionBankArea() {
        return collectionBankArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.collection_bank_area
     *
     * @param collectionBankArea the value for remittance.collection_bank_area
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setCollectionBankArea(String collectionBankArea) {
        this.collectionBankArea = collectionBankArea == null ? null : collectionBankArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.collection_bank_city
     *
     * @return the value of remittance.collection_bank_city
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getCollectionBankCity() {
        return collectionBankCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.collection_bank_city
     *
     * @param collectionBankCity the value for remittance.collection_bank_city
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setCollectionBankCity(String collectionBankCity) {
        this.collectionBankCity = collectionBankCity == null ? null : collectionBankCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.collection_bank_name
     *
     * @return the value of remittance.collection_bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getCollectionBankName() {
        return collectionBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.collection_bank_name
     *
     * @param collectionBankName the value for remittance.collection_bank_name
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setCollectionBankName(String collectionBankName) {
        this.collectionBankName = collectionBankName == null ? null : collectionBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.colletion_bank_accout
     *
     * @return the value of remittance.colletion_bank_accout
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getColletionBankAccout() {
        return collectionBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.colletion_bank_accout
     *
     * @param collectionBankAccount the value for remittance.colletion_bank_accout
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setColletionBankAccout(String collectionBankAccount) {
        this.collectionBankAccount = collectionBankAccount == null ? null : collectionBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.account_address
     *
     * @return the value of remittance.account_address
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getAccountAddress() {
        return accountAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.account_address
     *
     * @param accountAddress the value for remittance.account_address
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setAccountAddress(String accountAddress) {
        this.accountAddress = accountAddress == null ? null : accountAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.manageMent
     *
     * @return the value of remittance.manageMent
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public String getManagement() {
        return management;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.manageMent
     *
     * @param management the value for remittance.manageMent
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setManagement(String management) {
        this.management = management == null ? null : management.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remittance.product_line_id
     *
     * @return the value of remittance.product_line_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public Integer getProductLineId() {
        return productLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remittance.product_line_id
     *
     * @param productLineId the value for remittance.product_line_id
     *
     * @mbggenerated Tue Oct 18 14:55:34 CST 2022
     */
    public void setProductLineId(Integer productLineId) {
        this.productLineId = productLineId;
    }
}